### ISSUE TITLE
Task: Improve Error Reporting

### ISSUE THREAD

**Issue by J-Ziegler** [bsixel/Etheralt-Chat-Client#2]
Attempt to implement more diagnostically relevant error messages.

List of things that I say I'll do but never will: Separate error reporting into useful/friendly messages for the user, and more advanced messages logged for testing, debugging, whatever. Maybe a log file or something, eventually.

**Comment by bsixel** [comment]
There actually is built-in error logging to a file in the tools/FileHandler class. Something like FileHandler.writeToErrorLog(message).
