### ISSUE TITLE
Saving/Loading server properties does not work on UNIX machines.

### ISSUE THREAD

**Issue by bsixel** [bsixel/Etheralt-Chat-Client#4]
Only tested with Fedora so far, but seems to be a UNIX issue.

**Comment by bsixel** [comment]
Turns out it might just be the system I tested on. Issue closed.

**Comment by J-Ziegler** [comment]
Definitely an issue. Running the server from a clean setup results in errors. All files should probably be created and referenced based from the directory the initial server file exists in, for more general support. Poking around with it on my bit, don't really know what's going on.

http://pastebin.com/Jb6vU2dP

**Comment by bsixel** [comment]
Fixed the issue. The server was never calling the method that initially creates the preferences file and directories.
